import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, CircleHelp, Clock3, Globe2, MapPin, Plus, RotateCcw, Trash2, Wallet } from 'lucide-react'
import { directionClass, directionIcon, ErrorNotice, Loading, PanelTitle } from './components'
import { signed } from './api'
import type { CityContext, Decision, Validation } from './types'

export default function Builder({ context, decisions, setDecisions, validation, validating, validationError, retry, simulate, simulating, demo }: {
  context: CityContext; decisions: Decision[]; setDecisions: (decisions: Decision[]) => void
  validation: Validation | null; validating: boolean; validationError: string | null; retry: () => void
  simulate: () => void; simulating: boolean; demo: () => void
}) {
  const [filter, setFilter] = useState('Все направления')
  const directions = [...new Set(context.measures.map(m => m.direction))]
  const measures = context.measures.filter(m => filter === 'Все направления' || m.direction === filter)
  const toggle = (id: string) => {
    setDecisions(decisions.some(d => d.measure_id === id)
      ? decisions.filter(d => d.measure_id !== id)
      : [...decisions, { measure_id: id, district: null }])
  }
  return <div className="page-enter"><div className="page-heading"><div><div className="eyebrow">Ручной режим</div><h1>Соберите свою стратегию</h1><p>Выберите {context.constraints.decision_count} мероприятий и определите, где они нужнее всего.</p></div><button className="button secondary" onClick={demo}><RotateCcw size={16} /> Загрузить демо</button></div>
    <div className="builder-layout"><section><div className="filter-row" aria-label="Фильтр направлений">{['Все направления', ...directions].map(direction => <button key={direction} className={`filter-chip ${filter === direction ? 'active' : ''}`} aria-pressed={filter === direction} onClick={() => setFilter(direction)}>{direction !== 'Все направления' && directionIcon(direction, 15)}{direction}</button>)}</div><div className="measure-grid">{measures.map(measure => {
      const selection = decisions.find(d => d.measure_id === measure.id)
      return <article className={`measure-card ${selection ? 'selected' : ''}`} key={measure.id} data-testid={`measure-${measure.id}`}><div className="flex-between"><span className={`direction-tag ${directionClass(measure.direction)}`}>{directionIcon(measure.direction, 15)}{measure.direction}</span><span className="measure-id">{measure.id}</span></div><h2>{measure.name}</h2><div className="measure-meta"><span><Wallet size={14} />{measure.cost} ед.</span><span><Clock3 size={14} />лаг {measure.lag} кв.</span><span>{measure.scope === 'city' ? <Globe2 size={14} /> : <MapPin size={14} />}{measure.scope === 'city' ? 'Весь город' : 'Один район'}</span></div><div className="effect-chips">{Object.entries(measure.effects).map(([id, value]) => <span key={id} className={value < 0 ? 'negative-effect' : ''} title={context.indicators[id]?.name}>{id} {signed(value)}</span>)}</div><div className="measure-bottom">{selection && measure.scope === 'district' ? <label className="select-field"><span className="sr-only">Район для {measure.id}</span><MapPin size={15} /><select aria-label={`Район для ${measure.id}`} value={selection.district ?? ''} onChange={e => setDecisions(decisions.map(d => d.measure_id === measure.id ? { ...d, district: e.target.value || null } : d))}><option value="">Выберите район</option>{context.districts.map(d => <option key={d.name}>{d.name}</option>)}</select><ChevronDown size={14} /></label> : <span className="small muted">{selection ? 'Применится ко всем районам' : 'Полные эффекты до учёта лага'}</span>}<button aria-label={`${selection ? 'Убрать' : 'Добавить'} ${measure.id}`} aria-pressed={!!selection} onClick={() => toggle(measure.id)} className={`choose-button ${selection ? 'chosen' : ''}`}>{selection ? <Check size={17} /> : <Plus size={17} />}{selection ? 'Выбрано' : 'Выбрать'}</button></div></article>
    })}</div><details className="rules-details"><summary><CircleHelp size={16} />Как работают ограничения <ChevronDown size={16} /></summary><div><p>Бюджет: {context.budget} единиц. Выберите ровно {context.constraints.decision_count} разных мероприятий, максимум {context.constraints.max_per_direction} одного направления. Эффекты рассчитываются на {context.horizon} кварталов с учётом лагов.</p><ul>{context.constraints.incompatibilities.map((item, i) => <li key={i}>{item.measures.join(' + ')}: {item.same_district_only ? 'нельзя применять в одном районе' : 'нельзя выбирать вместе'}.{item.reason && ` ${item.reason}`}</li>)}</ul><p>Окончательную проверку каждого плана выполняет сервер.</p></div></details></section>
    <aside className="plan-sidebar panel"><PanelTitle eyebrow="ВАШ ПЛАН" title="Пять шагов вперёд" right={<span className="count-pill">{decisions.length}/{context.constraints.decision_count}</span>} /><div className="budget-box"><div className="flex-between"><span>Распределение бюджета</span><Wallet size={16} /></div><div className="budget-number">{validating ? <span className="budget-loading">Проверяем…</span> : <><strong>{validation?.budget.used ?? '—'}</strong><span>/ {context.budget}</span></>}</div><div className={`budget-track ${validation && validation.budget.remaining < 0 ? 'over' : ''}`}><i style={{ width: `${validation ? Math.min(100, validation.budget.used / context.budget * 100) : 0}%` }} /></div><div className="flex-between small"><span>Остаток</span><strong className={validation && validation.budget.remaining < 0 ? 'text-red' : ''}>{validating ? '…' : validation?.budget.remaining ?? '—'} ед.</strong></div></div>
    <div className="selected-list">{decisions.map((decision, index) => { const measure = context.measures.find(m => m.id === decision.measure_id)!; return <div className="selected-item" key={decision.measure_id}><span className="selection-index">{String(index + 1).padStart(2, '0')}</span><div><strong>{measure.name}</strong><span>{decision.district ?? (measure.scope === 'city' ? 'Весь город' : 'Район не выбран')} · {measure.cost} ед.</span></div><button className="icon-button" aria-label={`Удалить ${decision.measure_id} из плана`} onClick={() => toggle(decision.measure_id)}><Trash2 size={15} /></button></div>})}{Array.from({ length: Math.max(0, context.constraints.decision_count - decisions.length) }, (_, i) => <div className="empty-slot" key={i}><span>{String(decisions.length + i + 1).padStart(2, '0')}</span>Место для вашего решения</div>)}</div>
    <div className="validation-area" aria-live="polite">{validating ? <Loading>Проверяем план…</Loading> : validationError ? <ErrorNotice message={validationError} retry={retry} /> : validation?.valid ? <div className="valid-plan"><Check size={16} />План проверен. Можно рассчитывать.</div> : validation && decisions.length > 0 && <ul className="validation-errors">{validation.errors.map((error, i) => <li key={`${error.code}-${i}`}>{error.message}</li>)}</ul>}</div>
    <button className="button primary full" onClick={simulate} disabled={!validation?.valid || validating || simulating}>{simulating ? 'Рассчитываем…' : 'Рассчитать стратегию'}{!simulating && <ArrowRight size={17} />}</button>{decisions.length > 0 && <button className="text-button reset-plan" onClick={() => setDecisions([])} disabled={simulating}>Очистить выбор</button>}<p className="plan-footnote">Изменение плана обновляет проверку.<br />Результат появится после расчёта.</p></aside></div>
  </div>
}
